# This file was generated by GoReleaser. DO NOT EDIT.
cask "clyde" do
  desc "Terminal-based UI for monitoring Project Calico network flows in real-time"
  homepage "https://github.com/doucol/clyde/"
  version "0.4.5"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "clyde"

  on_macos do
    on_intel do
      url "https://github.com/doucol/clyde/releases/download/v0.4.5/clyde_Darwin_x86_64.tar.gz",
        using: :homebrew_curl
      sha256 "20bc4746a07acc34faae938d781a7b31cc14b80c8fbc82da71d392c806078357"
    end
    on_arm do
      url "https://github.com/doucol/clyde/releases/download/v0.4.5/clyde_Darwin_arm64.tar.gz",
        using: :homebrew_curl
      sha256 "da90d002fa5eefb2390e996482351a3d1765cb3e75054ae5a38ad9d96601db23"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/doucol/clyde/releases/download/v0.4.5/clyde_Linux_x86_64.tar.gz",
        using: :homebrew_curl
      sha256 "4025003dcaa71f798c40eb7058368eef5701b547a2b26b57d1417d62666af271"
    end
    on_arm do
      url "https://github.com/doucol/clyde/releases/download/v0.4.5/clyde_Linux_arm64.tar.gz",
        using: :homebrew_curl
      sha256 "6739fd8641c94c32d75c43b59fae8024706b636627147806ec28fa572a5e86aa"
    end
  end

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/clyde"]
    end
  end

  # No zap stanza required
end
