# This file was generated by GoReleaser. DO NOT EDIT.
cask "clyde" do
  desc "Terminal-based UI for monitoring Project Calico network flows in real-time"
  homepage "https://github.com/doucol/clyde/"
  version "0.4.6"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "clyde"

  on_macos do
    on_intel do
      url "https://github.com/doucol/clyde/releases/download/v0.4.6/clyde_Darwin_x86_64.tar.gz"
      sha256 "2109e81c3e502b7b1925dfc6b555e1d89399cd3bf19d804dd3f353aa9b13588f"
    end
    on_arm do
      url "https://github.com/doucol/clyde/releases/download/v0.4.6/clyde_Darwin_arm64.tar.gz"
      sha256 "cdcd97168c4ecc352324f0971c42d9edaed46fcae32397be4e0ba365d293f28e"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/doucol/clyde/releases/download/v0.4.6/clyde_Linux_x86_64.tar.gz"
      sha256 "296ea33cbd18cac84d87792a0c80419a74690698ed3ab6d98bdd2922878791dd"
    end
    on_arm do
      url "https://github.com/doucol/clyde/releases/download/v0.4.6/clyde_Linux_arm64.tar.gz"
      sha256 "acdd9d1e129a5e9e378cf95ddd70a6d346e6d76a2dc8709c7f41f963dda5b878"
    end
  end

  conflicts_with formula: [
      "clyde",
    ]

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/clyde"]
    end
  end

  # No zap stanza required
end
