# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class Clyde < Formula
  desc "Project calico observability tools"
  homepage "https://github.com/doucol/clyde"
  url "https://github.com/doucol/clyde/archive/refs/tags/v0.4.17.tar.gz"
  sha256 "076828423689b991df2f23d3b6c3f6cb413b39c0263c571068f0c7e7110c4e52"
  license "Apache-2.0"

  on_macos do
    on_intel do
      url "https://github.com/doucol/clyde/releases/download/v0.4.17/clyde-0.4.17-darwin-amd64.tar.gz"
      sha256 "f5c0d197e6a2a7c25081dbeecaa6be271f2cc84643c1b4788738c538e93b3a88"
    end

    on_arm do
      url "https://github.com/doucol/clyde/releases/download/v0.4.17/clyde-0.4.17-darwin-arm64.tar.gz"
      sha256 "3d83505aec12d9723b1a25dd84a49a0e180ccb86368f786a1b0289205df033b2"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/doucol/clyde/releases/download/v0.4.17/clyde-0.4.17-linux-amd64.tar.gz"
      sha256 "061fd38bae843efa5851e718a2a320149dabd73e689e7bab1eef992d0d76a526"
    end

    on_arm do
      url "https://github.com/doucol/clyde/releases/download/v0.4.17/clyde-0.4.17-linux-arm64.tar.gz"
      sha256 "28749d9f02011f1fdf2a4b20e38c8d2fcef57c8b264fcdf890676c0cc52857fb"
    end
  end

  def install
    bin.install clyde
  end

  test do
    assert_match("vv0.4.17", shell_output("clyde version"))
  end
end
