# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Clyde < Formula
  desc "Terminal-based UI for monitoring Project Calico network flows in real-time"
  homepage "https://github.com/doucol/clyde/"
  version "0.4.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/doucol/clyde/releases/download/v0.4.1/clyde_Darwin_x86_64.tar.gz", using: CurlDownloadStrategy
      sha256 "9b97c6f11d8c403ceeedfa84310060ad0391dea350e427eeb601347d2f2fb262"

      def install
        bin.install "clyde"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/doucol/clyde/releases/download/v0.4.1/clyde_Darwin_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "1f11fb382f1c3874902e59704e0ba71178e969c83059f295d2df08859d7fc431"

      def install
        bin.install "clyde"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/doucol/clyde/releases/download/v0.4.1/clyde_Linux_x86_64.tar.gz", using: CurlDownloadStrategy
      sha256 "1da577bc66568b0bce83e22dc923e3a607c6639f95e3f01a22e1f7163a0a42da"
      def install
        bin.install "clyde"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/doucol/clyde/releases/download/v0.4.1/clyde_Linux_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "01ff761eb39cd2e8a0ca07f0177351e3007382c583edce2d8d68807f80bba284"
      def install
        bin.install "clyde"
      end
    end
  end

  test do
    assert_match "v0.4.1", shell_output("#{bin}/clyde version")
  end
end
