# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Clyde < Formula
  desc "Terminal-based UI for monitoring Project Calico network flows in real-time"
  homepage "https://github.com/doucol/clyde/"
  version "0.4.2"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/doucol/clyde/releases/download/v0.4.2/clyde_Darwin_x86_64.tar.gz", using: CurlDownloadStrategy
      sha256 "49ad1b2276c9d1e3d5307a1eabd0b84ff0550a1e0dd19aa255724ab6c820e3a4"

      def install
        bin.install "clyde"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/doucol/clyde/releases/download/v0.4.2/clyde_Darwin_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "b9cff9c49290df1a4fe7ed2a7778b5a85766bcdecd1e63b2eb1ea18d075cbb6f"

      def install
        bin.install "clyde"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/doucol/clyde/releases/download/v0.4.2/clyde_Linux_x86_64.tar.gz", using: CurlDownloadStrategy
      sha256 "3073ebaca528aa6556cd6fbeec337b4ce3bfd7283bfa7830be8ccb9a78fca86b"
      def install
        bin.install "clyde"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/doucol/clyde/releases/download/v0.4.2/clyde_Linux_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "adb6f1d1f8b0f17ee62d4bbff0a6a5955a3d70c5bffc74fce8d9544e1111b1ca"
      def install
        bin.install "clyde"
      end
    end
  end

  test do
    assert_match "v0.4.2", shell_output("#{bin}/clyde version")
  end
end
